adaption: 'sotta'

update_every_x: 32
online: true
memory_type: "HUS"    # memory buffer 类型，可选 FIFO / Reservoir / PBRS / HUS

temperature: 1.0
loss_scaler: 0.0
inner_batch_size: 32                # 每个 mini-batch 的大小
learning_rate: 0.001          # 可选: 如不指定，将采用默认
weight_decay: 0.0             # 可选

use_learned_stats: false
bn_momentum: 0.01
use_sam: true
hus_threshold: 0.5

esm: false
log_grad: false

no_adapt: false
epoch: 1