adaption: 'sotta'

update_every_x: 32
online: true
memory_type: "HUS"    # memory buffer type, options: FIFO / Reservoir / PBRS / HUS

temperature: 1.0
loss_scaler: 0.0
inner_batch_size: 32                # size of each mini-batch
learning_rate: 0.001          # optional: if not specified, the default is used
weight_decay: 0.0             # optional

use_learned_stats: false
bn_momentum: 0.01
use_sam: true
hus_threshold: 0.5

esm: false
log_grad: false

no_adapt: false
epoch: 1