#-------------------------------------- dataset -----------------------------------------#
dataset: oppo
n_feature: 77
len_sw: 30
n_class: 17

n_domains: 4
n_target_domains: 1

#------------------------------------ training ------------------------------------------#
batch_size: 64
seed: 10
interval_validate: 25
out_path: './logs'
save_model: True

#-------------------------------------- model -------------------------------------------#
model: 'cnn'
res: false
resume: './ckpt'

alpha1: 0.1
alpha2: 0.1