#-------------------------------------- dataset -----------------------------------------#
# 指定使用的数据集为UCI数据集
dataset: uci
# 表示数据集中每个样本的特征数量为9
n_feature: 9
# 推测len_sw代表滑动窗口的长度，即每个样本的序列长度为128
len_sw: 128
# 表示数据集中的类别数量为6
n_class: 6

# 指定目标域的编号为1，在域适应问题中，明确了目标域
target_domain: 1
# 表示数据集中总共的域数量为4
n_domains: 4
# 表示目标域的数量为1
n_target_domains: 1

#------------------------------------ training -------------------------------------------#
# 指定训练时每个批次的样本数量为180
batch_size: 64
# 设置随机数种子为10，确保实验的可重复性
seed: 10
# 表示每训练25个批次进行一次验证
interval_validate: 25
# 指定训练日志的输出路径为当前目录下的logs文件夹
out_path: './logs'
# 表示训练过程中会保存模型
save_model: True

#-------------------------------------- model -------------------------------------------#
# 指定使用的模型为卷积神经网络（CNN）
model: 'cnn'
# 推测res表示是否使用残差结构，这里设置为False，即不使用残差结构
res: false
# 指定恢复训练时加载模型权重的路径为当前目录下的ckpt文件夹
resume: './ckpt'

